#!/bin/sh
#PBS -A winzeler-group
#PBS -N bam_dup_read_filter
#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -o /home/dwc001/scratch/logs
#PBS -e /home/dwc001/scratch/logs
#PBS -M dwc001@ucsd.edu
#PBS -m a
#PBS -t 1-4

bamnames_file=/projects/winzeler/ANALYSIS/DNAseq/test/bamnames_3D7_fix.txt
bam_dir=/projects/winzeler/ANALYSIS/DNAseq/Madeline/BAMS/missing_2023/3D7
output_dir=/projects/winzeler/ANALYSIS/DNAseq/test/bam_sam_filtered_daisy_3D7

readarray bamnames < $bamnames_file
bamnames=(null ${bamnames[@]}) # zero to one start index
bamname=${bamnames[$PBS_ARRAYID]}
echo $bamname

x=${bamname%.ready.bam}
y=${x##*/}
z=${y%.bam}
sample=${z##*/}
echo $sample

# ================================================================================

#samtools view -f97 -F1810 $bam_dir/$bamname > $output_dir/${sample}_DUP.sam
#samtools view -f81 -F1826 $bam_dir/$bamname >> $output_dir/${sample}_DUP.sam
#samtools view -f145 -F1826 $bam_dir/$bamname >> $output_dir/${sample}_DUP.sam
#samtools view -f161 -F1810 $bam_dir/$bamname >> $output_dir/${sample}_DUP.sam

samtools view -F 3854 $bam_dir/$bamname | awk '{if (($2==97||$2==81||$2==161||$2==145||$2==177||$2==113||$2==65||$2==129)) print }' > $output_dir/${sample}_INVDUP.sam

